### ISSUE TITLE
Grid does not render when getRowId is explicitly set to None

### ISSUE THREAD

**Issue by tlauli** [plotly/dash-ag-grid#417]
Affects dash-ag-grid version: 32.3.2, it worked in 31.3.1.

Ag grid fails to render when the `getRowId` argument is explicitly set to `None`, its default value.
```python
from dash import Dash
import dash_ag_grid as dag

layout = [
    dag.AgGrid(
        rowData=[{"test": 1}],
        columnDefs=[{"field": "test"}],
        getRowId=None,
    ),
]


app = Dash(__name__)
app.layout = layout
app.run(debug=True)
```
Error:
```
(This error originated from the built-in JavaScript code that runs Dash apps. Click to see the full stack trace or open your browser's console.)
TypeError: t is not a function

    at http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:1:15220

    at Io.setId (http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:50:29517)

    at Io.setDataAndId (http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:50:28743)

    at U1.createNode (http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:189:58137)

    at http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:189:54575

    at Array.map (<anonymous>)

    at U1.setRowData (http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:189:54559)

    at sv.setRowData (http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:189:72154)

    at sv.setInitialData (http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:189:61883)

    at sv.start (http://127.0.0.1:8050/_dash-component-suites/dash_ag_grid/async-community.js:189:61771)
```

**Comment by BSd3v** [comment]
I see the issue is with what the typing is placing, what is passed to the grid when you set a grid can be seen by using the `to_plotly_json()`, this will show the real default values:

```
from dash import Dash
import dash_ag_grid as dag

grid = dag.AgGrid(
        rowData=[{"test": 1}],
        columnDefs=[{"field": "test"}],
    )

print(grid.to_plotly_json())

layout = [
    grid,
]


app = Dash(__name__)
app.layout = layout
app.run(debug=True)
```

---

As far as `undefined` I find it counter intuitive to define something as `undefined`. But you are welcome to submit a PR on the dash repo to allow for the setting of an `undefined` value to a prop.

---

Also, going back to your example, I am a little confused but the `getRowId` which is the subject of the issue, but the example you provided is using `getRowStyle`. But I'm assuming the concept is the same... yes, you shouldnt pass a key to the grid unless it can handle a `null` in the upstream AG Grid.

**Comment by tlauli** [comment]
There should be `get_row_id`, I mistyped, edited the comment.

`undefined` may not be the best name, I agree, possibly something as `no_value` would be better.

When I have time I will make a new issue in the dash repo with the description of the problem and my proposed solution, and then try to implement it.
