### ISSUE TITLE
error message:  `dangerously_allow_code`

### ISSUE THREAD

**Issue by AtomicNess123** [plotly/dash-ag-grid#29]
Thanks for your work.

I followed the steps to test this tool, and encountered this error:

`TypeError: The `dash_ag_grid.AgGrid` component (version 2.0.0a1) with the ID "portfolio-grid" received an unexpected keyword argument: `dangerously_allow_code``

Thanks for any potential help provided!

**Comment by AnnMarieW** [comment]
Hi @AtomicNess123 
This is due to a change we are making in the next release.  I just updated the [demo app](https://github.com/plotly/dash-ag-grid/blob/dev/docs/demo_stock_portfolio.py) so it will  work with version 2.0.0a1.  Would you like to give it another try?

**Comment by AtomicNess123** [comment]
So basically, I git-clone it and try, correct?

**Comment by AnnMarieW** [comment]
The easy way to `pip install dash-ag-grid==2.0.0a1` then copy that demo app file and run it.  

Plus make sure you have at least the following:
dash>=2.0.0
pandas>=1.2.3
dash-bootstrap-components>=1.0.0
yfinance

If you are interested in contributing and would like to run the latest (unreleased) version, you can fork the repo and follow the instructions on how to build the component locally.

**Comment by AtomicNess123** [comment]
Thanks, how would installing using git clone be?

**Comment by AtomicNess123** [comment]
i basically wanted to run the python script and be able to edit it for my own purposes. Is that possible with this app?

**Comment by AnnMarieW** [comment]
Yes, you can do that - no need to clone the entire repo or build the component locally.  As I mentioned in my first reply, please just:
```
pip install dash-ag-grid==2.0.0a1
```

Copy this one file ( run it first to make sure it works) then change it however you like:
https://github.com/plotly/dash-ag-grid/blob/dev/docs/demo_stock_portfolio.py
